Repository SI705-SI63-Tayta/TP_Arqui_Web_Frontend, pull requests merged in 2024-11, with the labels that each got.

#12 mapmodal, stories of user
  Tayta/.gitignore
  Tayta/src/app/app.component.ts
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/appointment/creareditaappointment/creareditaappointment.component.css
  Tayta/src/app/components/appointment/creareditaappointment/creareditaappointment.component.html
  Tayta/src/app/components/appointment/creareditaappointment/creareditaappointment.component.ts
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.css
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.ts
  Tayta/src/app/components/dailyactivities/creareditardailyactivities/creareditardailyactivities.component.html
  Tayta/src/app/components/dailyactivities/creareditardailyactivities/creareditardailyactivities.component.ts
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.html
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.ts
  Tayta/src/app/components/mapmodal/mapmodal.component.css
  Tayta/src/app/components/mapmodal/mapmodal.component.html
  Tayta/src/app/components/mapmodal/mapmodal.component.ts
  Tayta/src/app/components/recipe/creaeditarecipe/creaeditarecipe.component.ts
  Tayta/src/app/components/recipe/listarrecipe/listarrecipe.component.css
  Tayta/src/app/components/recipe/listarrecipe/listarrecipe.component.html
  Tayta/src/app/components/recipe/listarrecipe/listarrecipe.component.ts
  Tayta/src/app/models/Appointment.ts
  Tayta/src/app/models/DailyActivities.ts
  Tayta/src/app/models/Recipe.ts
  Tayta/src/app/services/appointment.service.ts
  Tayta/src/app/services/dailyactivities.service.ts
  Tayta/src/app/services/recipe.service.ts
  Tayta/src/app/services/user.service.ts
  Tayta/src/environments/environments.ts
  Tayta/src/index.html
Labels: bug, enhancement

#19 role user listitems navbar and role doctor
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/appointment/creareditaappointment/creareditaappointment.component.html
  Tayta/src/app/components/appointment/creareditaappointment/creareditaappointment.component.ts
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.html
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.ts
  Tayta/src/app/components/clinicalhistorydetail/creareditarclinicalhistorydetail/creareditarclinicalhistorydetail.component.html
  Tayta/src/app/components/clinicalhistorydetail/creareditarclinicalhistorydetail/creareditarclinicalhistorydetail.component.ts
  Tayta/src/app/components/clinicalhistorydetail/listarclinicalhistorydetail/listarclinicalhistorydetail.component.html
  Tayta/src/app/components/clinicalhistorydetail/listarclinicalhistorydetail/listarclinicalhistorydetail.component.ts
  Tayta/src/app/components/dailyactivities/creareditardailyactivities/creareditardailyactivities.component.html
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.html
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.ts
  Tayta/src/app/components/medicalrecord/creaeditamedicalrecord/creaeditamedicalrecord.component.html
  Tayta/src/app/components/medicalrecord/listarmedicalrecord/listarmedicalrecord.component.html
  Tayta/src/app/components/medicalrecord/listarmedicalrecord/listarmedicalrecord.component.ts
  Tayta/src/app/components/notification/creareditarnotification/creareditarnotification.component.ts
  Tayta/src/app/components/recipe/listarrecipe/listarrecipe.component.html
  Tayta/src/app/components/review/creareditarreview/creareditarreview.component.html
  Tayta/src/app/components/review/creareditarreview/creareditarreview.component.ts
  Tayta/src/app/components/review/listarreview/listarreview.component.ts
  Tayta/src/app/components/toolbar/toolbar.component.css
  Tayta/src/app/components/toolbar/toolbar.component.html
  Tayta/src/app/components/toolbar/toolbar.component.ts
  Tayta/src/app/components/user/creareditaruser/creareditaruser.component.css
  Tayta/src/app/components/user/creareditaruser/creareditaruser.component.html
  Tayta/src/app/components/user/creareditaruser/creareditaruser.component.ts
  Tayta/src/app/models/Review.ts
  Tayta/src/app/services/appointment.service.ts
  Tayta/src/app/services/review.service.ts
  Tayta/src/app/services/user.service.ts
Labels: enhancement

#21 more options ver citas doctor enfermero
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.css
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.html
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.ts
  Tayta/src/app/components/menulanding/menulanding.component.css
  Tayta/src/app/components/recipe/creaeditarecipe/creaeditarecipe.component.ts
  Tayta/src/app/components/recipe/listarrecipe/listarrecipe.component.ts
  Tayta/src/app/services/recipe.service.ts
Labels: enhancement

#22 personal menu finish
  Tayta/.gitignore
  Tayta/angular.json
  Tayta/package.json
  Tayta/src/app/app.config.ts
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/toolbar/toolbar.component.css
  Tayta/src/app/components/toolbar/toolbar.component.html
  Tayta/src/app/components/toolbar/toolbar.component.ts
  Tayta/src/app/guard/seguridad.guard.ts
  Tayta/src/app/services/login.service.ts
  Tayta/src/environments/environments.ts
Labels: bug, enhancement

#24 reportes 2 queries renzo
  Tayta/package-lock.json
  Tayta/package.json
  Tayta/src/app/app.config.ts
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.css
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.html
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.html
  Tayta/src/app/components/medicalrecord/listarmedicalrecord/listarmedicalrecord.component.html
  Tayta/src/app/components/recipe-dialog/recipe-dialog.component.css
  Tayta/src/app/components/recipe-dialog/recipe-dialog.component.html
  Tayta/src/app/components/recipe-dialog/recipe-dialog.component.ts
  Tayta/src/app/components/recipe/creaeditarecipe/creaeditarecipe.component.ts
  Tayta/src/app/components/recipe/listarrecipe/listarrecipe.component.css
  Tayta/src/app/components/recipe/listarrecipe/listarrecipe.component.html
  Tayta/src/app/components/recipe/listarrecipe/listarrecipe.component.ts
  Tayta/src/app/components/register/register.component.html
  Tayta/src/app/components/register/register.component.ts
  Tayta/src/app/components/reportes/recipesfinishedclient/recipesfinishedclient.component.css
  Tayta/src/app/components/reportes/recipesfinishedclient/recipesfinishedclient.component.html
  Tayta/src/app/components/reportes/recipesfinishedclient/recipesfinishedclient.component.ts
  Tayta/src/app/components/reportes/reportes.component.css
  Tayta/src/app/components/reportes/reportes.component.html
  Tayta/src/app/components/reportes/reportes.component.ts
  Tayta/src/app/components/reportes/top5calificacion/top5calificacion.component.css
  Tayta/src/app/components/reportes/top5calificacion/top5calificacion.component.html
  Tayta/src/app/components/reportes/top5calificacion/top5calificacion.component.ts
  Tayta/src/app/components/review/creareditarreview/creareditarreview.component.html
  Tayta/src/app/components/review/creareditarreview/creareditarreview.component.ts
  Tayta/src/app/components/review/listarreview/listarreview.component.html
  Tayta/src/app/components/toolbar/toolbar.component.css
  Tayta/src/app/components/toolbar/toolbar.component.html
  Tayta/src/app/components/toolbar/toolbar.component.ts
  Tayta/src/app/components/user/creareditaruser/creareditaruser.component.html
  Tayta/src/app/models/QuantityRecipesFinishedPerClientDTO.ts
  Tayta/src/app/models/Top5PersonalDTO.ts
  Tayta/src/app/services/recipe.service.ts
  Tayta/src/app/services/review.service.ts
  Tayta/src/app/services/user.service.ts
Labels: enhancement

#25 Se realizaron los reportes
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/reportes/reportappointmentmode/reportappointmentmode.component.css
  Tayta/src/app/components/reportes/reportappointmentmode/reportappointmentmode.component.html
  Tayta/src/app/components/reportes/reportappointmentmode/reportappointmentmode.component.ts
  Tayta/src/app/components/reportes/reportquantityappointmentperiod/reportquantityappointmentperiod.component.css
  Tayta/src/app/components/reportes/reportquantityappointmentperiod/reportquantityappointmentperiod.component.html
  Tayta/src/app/components/reportes/reportquantityappointmentperiod/reportquantityappointmentperiod.component.ts
  Tayta/src/app/components/toolbar/toolbar.component.ts
  Tayta/src/app/models/AppointmentCountDTO.ts
  Tayta/src/app/models/AppointmentModeDTO.ts
  Tayta/src/app/services/appointment.service.ts
Labels: enhancement

#26 query 1
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/reportes/historiaclinicaperiodo/historiaclinicaperiodo.component.css
  Tayta/src/app/components/reportes/historiaclinicaperiodo/historiaclinicaperiodo.component.html
  Tayta/src/app/components/reportes/historiaclinicaperiodo/historiaclinicaperiodo.component.ts
  Tayta/src/app/components/reportes/resenamayor3/resenamayor3.component.css
  Tayta/src/app/components/reportes/resenamayor3/resenamayor3.component.html
  Tayta/src/app/components/reportes/resenamayor3/resenamayor3.component.ts
  Tayta/src/app/services/review.service.ts
Labels: enhancement

#27 register user findni and findusername in userservice fixed
  Tayta/src/app/services/user.service.ts
Labels: bug

#30 query 2
  Tayta/src/app/app.component.ts
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/reportes/historiaclinicaperiodo/historiaclinicaperiodo.component.css
  Tayta/src/app/components/reportes/historiaclinicaperiodo/historiaclinicaperiodo.component.html
  Tayta/src/app/components/reportes/historiaclinicaperiodo/historiaclinicaperiodo.component.ts
  Tayta/src/app/models/MedicalRecordDateDTO.ts
  Tayta/src/app/services/medicalrecord.service.ts
  Tayta/src/app/services/review.service.ts
Labels: enhancement

#32 arreglo de query 2
  Tayta/src/app/models/MedicalRecordDateDTO.ts
Labels: enhancement
