Repository SI705-SI63-Tayta/TP_Arqui_Web_Frontend, pull requests merged in 2024-10, with the labels that each got.

#1 raiz y view,services
  Tayta/.editorconfig
  Tayta/.gitignore
  Tayta/.vscode/extensions.json
  Tayta/.vscode/launch.json
  Tayta/.vscode/tasks.json
  Tayta/README.md
  Tayta/angular.json
  Tayta/package-lock.json
  Tayta/package.json
  Tayta/public/favicon.ico
  Tayta/server.ts
  Tayta/src/app/app.component.css
  Tayta/src/app/app.component.html
  Tayta/src/app/app.component.spec.ts
  Tayta/src/app/app.component.ts
  Tayta/src/app/app.config.server.ts
  Tayta/src/app/app.config.ts
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/viewrole/viewrole.component.css
  Tayta/src/app/components/viewrole/viewrole.component.html
  Tayta/src/app/components/viewrole/viewrole.component.ts
  Tayta/src/app/components/viewuser/viewuser.component.css
  Tayta/src/app/components/viewuser/viewuser.component.html
  Tayta/src/app/components/viewuser/viewuser.component.ts
  Tayta/src/app/services/usuario.service.ts
  Tayta/src/environments/envionments.ts
  Tayta/src/index.html
  Tayta/src/main.server.ts
  Tayta/src/main.ts
  Tayta/src/styles.css
  Tayta/tsconfig.app.json
  Tayta/tsconfig.json
  Tayta/tsconfig.spec.json
Labels: enhancement

#2 dailyact, role, user lis with angular mat
  Tayta/angular.json
  Tayta/package-lock.json
  Tayta/package.json
  Tayta/src/app/app.component.html
  Tayta/src/app/app.component.ts
  Tayta/src/app/app.config.ts
  Tayta/src/app/components/dailyactivities/dailyactivities.component.css
  Tayta/src/app/components/dailyactivities/dailyactivities.component.html
  Tayta/src/app/components/dailyactivities/dailyactivities.component.ts
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.css
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.html
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.ts
  Tayta/src/app/components/role/listarrole/listarrole.component.css
  Tayta/src/app/components/role/listarrole/listarrole.component.html
  Tayta/src/app/components/role/listarrole/listarrole.component.ts
  Tayta/src/app/components/role/role.component.css
  Tayta/src/app/components/role/role.component.html
  Tayta/src/app/components/role/role.component.ts
  Tayta/src/app/components/user/listaruser/listaruser.component.css
  Tayta/src/app/components/user/listaruser/listaruser.component.html
  Tayta/src/app/components/user/listaruser/listaruser.component.ts
  Tayta/src/app/components/user/user.component.css
  Tayta/src/app/components/user/user.component.html
  Tayta/src/app/components/user/user.component.ts
  Tayta/src/app/components/viewrole/viewrole.component.html
  Tayta/src/app/components/viewrole/viewrole.component.ts
  Tayta/src/app/components/viewuser/viewuser.component.html
  Tayta/src/app/components/viewuser/viewuser.component.ts
  Tayta/src/app/models/DailyActivities.ts
  Tayta/src/app/models/Role.ts
  Tayta/src/app/models/User.ts
  Tayta/src/app/services/dailyactivities.service.ts
  Tayta/src/app/services/role.service.ts
  Tayta/src/app/services/user.service.ts
  Tayta/src/app/services/usuario.service.ts
  Tayta/src/environments/envionments.ts
  Tayta/src/index.html
  Tayta/src/styles.css
Labels: bug, enhancement

#3 name env fix
  Tayta/src/app/app.component.html
  Tayta/src/app/app.component.ts
  Tayta/src/app/services/dailyactivities.service.ts
  Tayta/src/app/services/role.service.ts
  Tayta/src/app/services/user.service.ts
  Tayta/src/environments/environments.ts
Labels: bug

#4 implement the MedicalRecord class, typescript and html
  Tayta/src/app/app.component.html
  Tayta/src/app/app.component.ts
  Tayta/src/app/components/medicalrecord/listarmedicalrecord/listarmedicalrecord.component.css
  Tayta/src/app/components/medicalrecord/listarmedicalrecord/listarmedicalrecord.component.html
  Tayta/src/app/components/medicalrecord/listarmedicalrecord/listarmedicalrecord.component.ts
  Tayta/src/app/components/medicalrecord/medicalrecord.component.css
  Tayta/src/app/components/medicalrecord/medicalrecord.component.html
  Tayta/src/app/components/medicalrecord/medicalrecord.component.ts
  Tayta/src/app/models/MedicalRecord.ts
  Tayta/src/app/services/medicalrecord.service.ts
  package-lock.json
Labels: enhancement

#5 Appointment y Recipe
  Tayta/src/app/components/appointment/appointment.component.css
  Tayta/src/app/components/appointment/appointment.component.html
  Tayta/src/app/components/appointment/appointment.component.ts
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.css
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.html
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.ts
  Tayta/src/app/components/recipe/recipe.component.css
  Tayta/src/app/components/recipe/recipe.component.html
  Tayta/src/app/components/recipe/recipe.component.ts
  Tayta/src/app/components/recipe/viewrecipe/viewrecipe.component.css
  Tayta/src/app/components/recipe/viewrecipe/viewrecipe.component.html
  Tayta/src/app/components/recipe/viewrecipe/viewrecipe.component.ts
  Tayta/src/app/models/Appointment.ts
  Tayta/src/app/models/Recipe.ts
  Tayta/src/app/services/appointment.service.ts
  Tayta/src/app/services/recipe.service.ts
Labels: enhancement

#6 Añadí el frontend de detalle de historia clínica y de recetas
  Tayta/src/app/app.component.html
  Tayta/src/app/app.component.ts
  Tayta/src/app/app.config.ts
  Tayta/src/app/components/appointment/appointment.component.css
  Tayta/src/app/components/appointment/appointment.component.html
  Tayta/src/app/components/appointment/appointment.component.ts
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.css
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.html
  Tayta/src/app/components/appointment/listar-appointment/listar-appointment.component.ts
  Tayta/src/app/components/clinicalhistorydetail/clinicalhistorydetail.component.css
  Tayta/src/app/components/clinicalhistorydetail/clinicalhistorydetail.component.html
  Tayta/src/app/components/clinicalhistorydetail/clinicalhistorydetail.component.ts
  Tayta/src/app/components/clinicalhistorydetail/listarclinicalhistorydetail/listarclinicalhistorydetail.component.css
  Tayta/src/app/components/clinicalhistorydetail/listarclinicalhistorydetail/listarclinicalhistorydetail.component.html
  Tayta/src/app/components/clinicalhistorydetail/listarclinicalhistorydetail/listarclinicalhistorydetail.component.ts
  Tayta/src/app/components/recipe/recipe.component.css
  Tayta/src/app/components/recipe/recipe.component.html
  Tayta/src/app/components/recipe/recipe.component.ts
  Tayta/src/app/components/recipe/viewrecipe/viewrecipe.component.css
  Tayta/src/app/components/recipe/viewrecipe/viewrecipe.component.html
  Tayta/src/app/components/recipe/viewrecipe/viewrecipe.component.ts
  Tayta/src/app/models/Appointment.ts
  Tayta/src/app/models/ClinicalHistoryDetail.ts
  Tayta/src/app/models/Recipe.ts
  Tayta/src/app/services/appointment.service.ts
  Tayta/src/app/services/clinicaldetailhistory.service.ts
  Tayta/src/app/services/recipe.service.ts
  Tayta/src/styles.css
Labels: enhancement

#11 añadiendo creareditar de Detalle de Historia Clínica y modificando Daily Activities
  Tayta/src/app/app.routes.ts
  Tayta/src/app/components/clinicalhistorydetail/clinicalhistorydetail.component.ts
  Tayta/src/app/components/clinicalhistorydetail/creareditarclinicalhistorydetail/creareditarclinicalhistorydetail.component.css
  Tayta/src/app/components/clinicalhistorydetail/creareditarclinicalhistorydetail/creareditarclinicalhistorydetail.component.html
  Tayta/src/app/components/clinicalhistorydetail/creareditarclinicalhistorydetail/creareditarclinicalhistorydetail.component.ts
  Tayta/src/app/components/clinicalhistorydetail/listarclinicalhistorydetail/listarclinicalhistorydetail.component.html
  Tayta/src/app/components/clinicalhistorydetail/listarclinicalhistorydetail/listarclinicalhistorydetail.component.ts
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.html
  Tayta/src/app/components/dailyactivities/listardailyactivities/listardailyactivities.component.ts
  Tayta/src/app/services/clinicaldetailhistory.service.ts
  Tayta/src/app/services/dailyactivities.service.ts
Labels: enhancement
